name: Test Remote Helper

on:
  push:
    paths:
      - git-remote-evm/**
      - wallet-bridge/**
      - on-chain/contracts/**
  pull_request:
    paths:
      - git-remote-evm/**
      - wallet-bridge/**
      - on-chain/contracts/**
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # This is needed for integration tests which use git
    - name: Setup git config
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install on-chain dependencies
      run: npm install
      working-directory: on-chain
    - name: Build remote-helper
      run: cargo build --verbose
      working-directory: git-remote-evm
    # TODO: Make it work without --test-threads=1
    # This is a workaround needed to make it work with hardhat's test node
    # There's a nonce mismatch when running tests in parallel
    - name: Run tests
      run: |
        (cd ../on-chain && npx hardhat node) &
        sleep 5 &&
        cargo test --verbose -- --test-threads=1
      working-directory: git-remote-evm

