name: Test Remote Helper

on:
  push:
    paths:
      - git-remote-evm/**
      - wallet-bridge/**
  pull_request:
    paths:
      - git-remote-evm/**
      - wallet-bridge/**

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./git-remote-evm

    steps:
    # This is needed for integration tests which use git
    - name: Setup git config
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

