name: Test Remote Helper

on:
  push:
    paths:
      - git-remote-evm/**
      - wallet-bridge/**
      - on-chain/contracts/**
  pull_request:
    paths:
      - git-remote-evm/**
      - wallet-bridge/**
      - on-chain/contracts/**
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # This is needed for integration tests which use git
    - name: Setup git config
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Build
      run: cargo build --verbose
      working-directory: git-remote-evm
    - name: Run tests
      run: cargo test --verbose
      working-directory: git-remote-evm

